### ISSUE TITLE
Tests for different versions Keras

### ISSUE THREAD

**Issue by snormore** [triagemd/model-converters#7]
I noticed some failures when writing tests in the Lab, depending on the version of Keras.

The only version I tried that made it through the run was `Keras==2.0.8`. 

### `Keras==1`

```
Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 funcsigs-1.0.2 h5py-2.7.0 html5lib-0.9999999 keras-1.0.0 markdown-2.6.9 mock-2.0.0 model-converters-0.0.3 numpy-1.13.1 pbr-3.1.1 protobuf-3.4.0 pyyaml-3.12 scipy-0.19.1 tensorflow-1.3.0 tensorflow-tensorboard-0.1.5 theano-0.9.0 werkzeug-0.12.2
Traceback (most recent call last):
  File "/usr/local/bin/keras_to_tensorflow", line 10, in <module>
    KerasToTensorflow.convert(sys.argv[1], sys.argv[2])
  File "/usr/local/lib/python2.7/dist-packages/model_converters/keras_to_tensorflow.py", line 20, in convert
    model = KerasToTensorflow.load_keras_model(model_path)
  File "/usr/local/lib/python2.7/dist-packages/model_converters/keras_to_tensorflow.py", line 10, in load_keras_model
    return keras.models.load_model(model_path, custom_objects={
AttributeError: 'module' object has no attribute 'models'
```

### `Keras==2`

```
Traceback (most recent call last):
  File "/usr/local/bin/keras_to_tensorflow", line 10, in <module>
    KerasToTensorflow.convert(sys.argv[1], sys.argv[2])
  File "/usr/local/lib/python2.7/dist-packages/model_converters/keras_to_tensorflow.py", line 20, in convert
    model = KerasToTensorflow.load_keras_model(model_path)
  File "/usr/local/lib/python2.7/dist-packages/model_converters/keras_to_tensorflow.py", line 12, in load_keras_model
    'relu6': keras.applications.mobilenet.relu6,
AttributeError: 'module' object has no attribute 'mobilenet'
```

We might want to consider only supporting `2.0.8` forward at this point.

cc @stephensolis

**Comment by stephensolis** [comment]
Mobilenet support was introduced with Keras 2.0.6 ([release notes](https://github.com/fchollet/keras/releases/tag/2.0.6)), that's why that was failing.

However, the APIs this converter actually depends on are present since Keras 1.0.7 (relatively trivial patches would be needed for older versions, but considering its age, I think that's a good cutoff point).

(Tensorflow's SavedModels were also introduced in 0.12.0, but since TF older than that was not distributed on PyPI, it's not such a big deal)
